DELIMITER //

DROP PROCEDURE IF EXISTS sp_ALTERA_TIPO_ENDERECO //

CREATE PROCEDURE sp_ALTERA_TIPO_ENDERECO (
    IN p_ID_TIPO_ENDERECO TINYINT,
    IN p_DESCRICAO_TIPO_ENDERECO VARCHAR(25),
    IN p_LOG_ID_USUARIO SMALLINT
)
BEGIN
    UPDATE TIPOS_ENDERECO
       SET DESCRICAO_TIPO_ENDERECO = p_DESCRICAO_TIPO_ENDERECO,
           LOG_ID_USUARIO          = p_LOG_ID_USUARIO,
           LOG_ROTINA              = 'A',
           LOG_DATA_HORA           = CURRENT_TIMESTAMP
     WHERE ID_TIPO_ENDERECO = p_ID_TIPO_ENDERECO;
END //

DELIMITER ;
