DELIMITER //

DROP PROCEDURE IF EXISTS sp_CONSULTA_USUARIO //

CREATE PROCEDURE sp_CONSULTA_USUARIO (
    IN p_NOME_USUARIO VARCHAR(30),
    IN p_SENHA        VARCHAR(30)
)
BEGIN
    SELECT ID_USUARIO,
           NOME_USUARIO,
           PRIVILEGIO,
           INATIVO,
           DATA_INICIO,
           DATA_EXPIRACAO,
           QUANTIDADE_CONEXOES,
           QUANTIDADE_CONECTADO,
           ALTERAR_SENHA_PRIMEIRO_LOGON,
           SENHA_POR_TRINTA_DIAS
      FROM USUARIOS
     WHERE NOME_USUARIO = p_NOME_USUARIO
       AND SENHA        = p_SENHA;
END //

DELIMITER ;
