DROP PROCEDURE IF EXISTS sp_EXCLUI_TIPO_TELEFONE;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_TIPO_TELEFONE(
    IN p_ID_TIPO_TELEFONE    TINYINT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE TIPOS_TELEFONE
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = NOW(),
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_TIPO_TELEFONE = p_ID_TIPO_TELEFONE;

    DELETE FROM TIPOS_TELEFONE
     WHERE ID_TIPO_TELEFONE = p_ID_TIPO_TELEFONE;
END //

DELIMITER ;
