DROP PROCEDURE IF EXISTS sp_CONSULTA_TIPOS_ENDERECO;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_TIPOS_ENDERECO ()
BEGIN
    SELECT ID_TIPO_ENDERECO,
           DESCRICAO_TIPO_ENDERECO
      FROM TIPOS_ENDERECO
     ORDER BY ID_TIPO_ENDERECO;
END //

DELIMITER ;
