DROP PROCEDURE IF EXISTS sp_CONSULTA_PAIS;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_PAIS (
    IN p_ID_PAIS SMALLINT
)
BEGIN
    SELECT ID_PAIS,
           NOME_PAIS,
           SIGLA02,
           SIGLA03,
           CODIGO_ISO3166,
           NUMERO_DDI,
           INATIVO
      FROM PAISES
     WHERE ID_PAIS = p_ID_PAIS;
END//

DELIMITER ;
