DROP PROCEDURE IF EXISTS sp_EXCLUI_PAIS;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_PAIS (
    IN p_ID_PAIS             SMALLINT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE PAISES
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = NOW(),
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_PAIS = p_ID_PAIS;

    DELETE FROM PAISES
     WHERE ID_PAIS = p_ID_PAIS;
END//

DELIMITER ;
