DROP PROCEDURE IF EXISTS sp_INSERE_ESTADO_CIVIL;

DELIMITER //

CREATE PROCEDURE sp_INSERE_ESTADO_CIVIL (
    IN p_DESCRICAO_ESTADO_CIVIL VARCHAR(25),
    IN p_LOG_ID_USUARIO         SMALLINT,
    OUT p_ID_ESTADO_CIVIL       TINYINT
)
BEGIN
    INSERT INTO ESTADOS_CIVIS (
        DESCRICAO_ESTADO_CIVIL,
        LOG_ID_USUARIO,
        LOG_ROTINA
    ) VALUES (
        p_DESCRICAO_ESTADO_CIVIL,
        p_LOG_ID_USUARIO,
        'I'
    );

    SET p_ID_ESTADO_CIVIL = LAST_INSERT_ID();
END//

DELIMITER ;
