DROP PROCEDURE IF EXISTS sp_CONSULTA_ESTADO_CIVIL;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_ESTADO_CIVIL (
    IN p_ID_ESTADO_CIVIL TINYINT
)
BEGIN
    SELECT ID_ESTADO_CIVIL,
           DESCRICAO_ESTADO_CIVIL
      FROM ESTADOS_CIVIS
     WHERE ID_ESTADO_CIVIL = p_ID_ESTADO_CIVIL;
END//

DELIMITER ;
