DROP PROCEDURE IF EXISTS sp_INSERE_ESTADO;

DELIMITER //

CREATE PROCEDURE sp_INSERE_ESTADO (
    IN p_ID_PAIS        SMALLINT,
    IN p_NOME_ESTADO    VARCHAR(20),
    IN p_SIGLA_ESTADO   CHAR(2),
    IN p_CODIGO_IBGE    TINYINT,
    IN p_INATIVO        BIT,
    IN p_LOG_ID_USUARIO SMALLINT,
    OUT p_ID_ESTADO     SMALLINT
)
BEGIN
    INSERT INTO ESTADOS (
        ID_PAIS,
        NOME_ESTADO,
        SIGLA_ESTADO,
        CODIGO_IBGE,
        INATIVO,
        LOG_ID_USUARIO,
        LOG_ROTINA
    ) VALUES (
        p_ID_PAIS,
        p_NOME_ESTADO,
        p_SIGLA_ESTADO,
        p_CODIGO_IBGE,
        p_INATIVO,
        p_LOG_ID_USUARIO,
        'I'
    );

    SET p_ID_ESTADO = LAST_INSERT_ID();
END//

DELIMITER ;
