DROP PROCEDURE IF EXISTS sp_CONSULTA_ESTADO;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_ESTADO (
    IN p_ID_ESTADO   SMALLINT,
    IN p_NOME_ESTADO VARCHAR(20)
)
BEGIN
    SELECT ID_ESTADO,
           ID_PAIS,
           NOME_ESTADO,
           SIGLA_ESTADO,
           CODIGO_IBGE,
           INATIVO
      FROM ESTADOS
     WHERE ID_ESTADO   = p_ID_ESTADO
        OR NOME_ESTADO = p_NOME_ESTADO;
END//

DELIMITER ;
