DROP PROCEDURE IF EXISTS sp_CONSULTA_TIPOS_ZONA;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_TIPOS_ZONA()
BEGIN
    SELECT ID_TIPO_ZONA,
           DESCRICAO_TIPO_ZONA
      FROM TIPOS_ZONA
     ORDER BY ID_TIPO_ZONA;
END//

DELIMITER ;
