DROP PROCEDURE IF EXISTS sp_EXCLUI_TIPO_ZONA;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_TIPO_ZONA(
    IN p_ID_TIPO_ZONA        TINYINT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE TIPOS_ZONA
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = CURRENT_TIMESTAMP,
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_TIPO_ZONA = p_ID_TIPO_ZONA;

    DELETE FROM TIPOS_ZONA
     WHERE ID_TIPO_ZONA = p_ID_TIPO_ZONA;
END//

DELIMITER ;
