DROP PROCEDURE IF EXISTS sp_ALTERA_CIDADE;

DELIMITER //

CREATE PROCEDURE sp_ALTERA_CIDADE(
    IN p_ID_CIDADE      SMALLINT,
    IN p_ID_ESTADO      SMALLINT,
    IN p_NOME_CIDADE    VARCHAR(45),
    IN p_CODIGO_IBGE    INTEGER,
    IN p_NUMERO_DDD     TINYINT,
    IN p_INATIVA        BIT,
    IN p_LOG_ID_USUARIO SMALLINT
)
BEGIN
    UPDATE CIDADES
       SET ID_ESTADO      = p_ID_ESTADO,
           NOME_CIDADE    = p_NOME_CIDADE,
           CODIGO_IBGE    = p_CODIGO_IBGE,
           NUMERO_DDD     = p_NUMERO_DDD,
           INATIVA        = p_INATIVA,
           LOG_ID_USUARIO = p_LOG_ID_USUARIO,
           LOG_ROTINA     = 'A',
           LOG_DATA_HORA  = NOW()
     WHERE ID_CIDADE = p_ID_CIDADE;
END//

DELIMITER ;
