DROP PROCEDURE IF EXISTS sp_CONSULTA_TIPO_ZONA;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_TIPO_ZONA(
    IN p_ID_TIPO_ZONA TINYINT
)
BEGIN
    SELECT ID_TIPO_ZONA,
           DESCRICAO_TIPO_ZONA
      FROM TIPOS_ZONA
     WHERE ID_TIPO_ZONA = p_ID_TIPO_ZONA;
END//

DELIMITER ;
