DROP PROCEDURE IF EXISTS sp_CONSULTA_CIDADE;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_CIDADE(
    IN p_ID_CIDADE   SMALLINT,
    IN p_NOME_CIDADE VARCHAR(45)
)
BEGIN
    SELECT ID_CIDADE,
           ID_ESTADO,
           NOME_CIDADE,
           CODIGO_IBGE,
           NUMERO_DDD,
           INATIVA,
           LOG_ID_USUARIO,
           LOG_ROTINA,
           LOG_DATA_HORA,
           LOG_MOTIV_OEXCLUSAO
      FROM CIDADES
     WHERE ID_CIDADE   = p_ID_CIDADE
        OR NOME_CIDADE = p_NOME_CIDADE;
END//

DELIMITER ;
