DROP PROCEDURE IF EXISTS sp_CONSULTA_CIDADES;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_CIDADES(
    IN p_NOME_CIDADE VARCHAR(45),
    IN p_INATIVA     BIT
)
BEGIN
    SELECT ID_CIDADE,
           ID_ESTADO,
           NOME_CIDADE,
           CODIGO_IBGE,
           NUMERO_DDD,
           INATIVA,
           NOME_ESTADO
      FROM vw_CIDADES_ESTADOS
     WHERE INATIVA = p_INATIVA
       AND NOME_CIDADE LIKE p_NOME_CIDADE;
END//

DELIMITER ;
