DROP PROCEDURE IF EXISTS sp_CONSULTA_ZONA;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_ZONA(
    IN p_ID_ZONA SMALLINT
)
BEGIN
   SELECT ID_ZONA,
          ID_TIPO_ZONA,
          DESCRICAO_ZONA,
          INATIVA,
          AREA_MINIMA,
          TESTADA_MINIMA,
          COMPLEMENTO_AREA_MINIMA,
          IDENTIFICADOR_ZONA
     FROM ZONAS
    WHERE ID_ZONA = p_ID_ZONA;
END//

DELIMITER ;
