DROP PROCEDURE IF EXISTS sp_CONSULTA_DISTRITOS;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_DISTRITOS(
    IN p_NOME_DISTRITO VARCHAR(50),
    IN p_INATIVO       BIT
)
BEGIN
    SELECT ID_DISTRITO,
           ID_CIDADE,
           NOME_DISTRITO,
           INATIVO,
           NOME_CIDADE
      FROM vw_DISTRITOS_CIDADES
     WHERE INATIVO = p_INATIVO
       AND NOME_DISTRITO LIKE p_NOME_DISTRITO;
END//

DELIMITER ;
