DROP PROCEDURE IF EXISTS sp_ALTERA_BAIRRO;

DELIMITER //

CREATE PROCEDURE sp_ALTERA_BAIRRO(
    IN p_ID_BAIRRO      INT,
    IN p_ID_CIDADE      SMALLINT,
    IN p_NOME_BAIRRO    VARCHAR(70),
    IN p_DATA_VIGORACAO DATETIME,
    IN p_INATIVO        BIT,
    IN p_LOG_ID_USUARIO SMALLINT
)
BEGIN
    UPDATE BAIRROS
       SET ID_CIDADE      = p_ID_CIDADE,
           NOME_BAIRRO    = p_NOME_BAIRRO,
           DATA_VIGORACAO = p_DATA_VIGORACAO,
           INATIVO        = p_INATIVO,
           LOG_ID_USUARIO = p_LOG_ID_USUARIO,
           LOG_ROTINA     = 'A',
           LOG_DATA_HORA  = NOW()
     WHERE ID_BAIRRO = p_ID_BAIRRO;
END//

DELIMITER ;
