DROP PROCEDURE IF EXISTS sp_EXCLUI_DISTRITO;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_DISTRITO(
    IN p_ID_DISTRITO         SMALLINT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE DISTRITOS
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = NOW(),
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_DISTRITO = p_ID_DISTRITO;

    DELETE FROM DISTRITOS
     WHERE ID_DISTRITO = p_ID_DISTRITO;
END//

DELIMITER ;
