CREATE TABLE IF NOT EXISTS LOGRADOUROS (
    ID_LOGRADOURO SMALLINT AUTO_INCREMENT NOT NULL,
    DESCRICAO_LOGRADOURO VARCHAR(25) NULL,
    ABREVIATURA_LOGRADOURO VARCHAR(10) NULL,
    INATIVO BIT DEFAULT 0,
    LOG_ID_USUARIO SMALLINT NOT NULL,
    LOG_ROTINA VARCHAR(1) NOT NULL,
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    LOG_MOTIVO_EXCLUSAO TEXT NULL,
    CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
    CONSTRAINT PK_LOGRADOUROS PRIMARY KEY (ID_LOGRADOURO),
    CONSTRAINT FK_LOGRADOUROS_USUARIOS FOREIGN KEY (LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
