DROP PROCEDURE IF EXISTS sp_CONSULTA_BAIRROS;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_BAIRROS(
    IN p_NOME_BAIRRO VARCHAR(70),
    IN p_INATIVO     BIT
)
BEGIN
    SELECT ID_BAIRRO,
           ID_CIDADE,
           NOME_BAIRRO,
           DATA_VIGORACAO,
           INATIVO,
           NOME_CIDADE
      FROM vw_BAIRROS_CIDADES
     WHERE INATIVO = p_INATIVO
       AND NOME_BAIRRO LIKE p_NOME_BAIRRO;
END//

DELIMITER ;
