DROP PROCEDURE IF EXISTS sp_EXCLUI_QUADRA;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_QUADRA(
    IN p_ID_QUADRA           SMALLINT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE QUADRAS
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_QUADRA = p_ID_QUADRA;

    DELETE FROM QUADRAS
     WHERE ID_QUADRA = p_ID_QUADRA;
END//

DELIMITER ;
