DROP PROCEDURE IF EXISTS sp_CONSULTA_VIA;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_VIA(
    IN p_ID_VIA INT,
    IN p_CEP    CHAR(8)
)
BEGIN
    SELECT ID_VIA,
           ID_LOGRADOURO,
           ID_BAIRRO,
           NOME_VIA,
           CEP,
           INATIVA
      FROM VIAS
     WHERE ID_VIA = p_ID_VIA
        OR CEP    = p_CEP;
END//

DELIMITER ;
