DROP PROCEDURE IF EXISTS sp_CONSULTA_VIAS;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_VIAS(
    IN p_NOME_VIA  VARCHAR(60),
    IN p_ID_BAIRRO INT,
    IN p_INATIVA   BIT
)
BEGIN
    SELECT ID_VIA,
           ID_LOGRADOURO,
           ID_BAIRRO,
           NOME_VIA,
           CEP,
           INATIVA,
           NOME_BAIRRO,
           DESCRICAO_LOGRADOURO
      FROM vw_VIAS_BAIRROS
     WHERE INATIVA   = p_INATIVA
       AND ID_BAIRRO = p_ID_BAIRRO
       AND NOME_VIA LIKE p_NOME_VIA;
END//

DELIMITER ;
