DROP PROCEDURE IF EXISTS sp_EXCLUI_LOTE;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_LOTE(
    IN p_ID_LOTE             SMALLINT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE LOTES
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = NOW(),
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_LOTE = p_ID_LOTE;

    DELETE FROM LOTES
     WHERE ID_LOTE = p_ID_LOTE;
END//

DELIMITER ;
