DROP VIEW IF EXISTS vw_CONDOMINIOS_BAIRROS;

CREATE VIEW vw_CONDOMINIOS_BAIRROS AS
   SELECT CONDOMINIOS.ID_CONDOMINIO,
          CONDOMINIOS.ID_BAIRRO,
          CONDOMINIOS.NOME_CONDOMINIO,
          CONDOMINIOS.INATIVO,
          BAIRROS.NOME_BAIRRO
     FROM CONDOMINIOS
    INNER JOIN BAIRROS
       ON BAIRROS.ID_BAIRRO = CONDOMINIOS.ID_BAIRRO;
