DELIMITER //

DROP PROCEDURE IF EXISTS sp_CONSULTA_USUARIOS //

CREATE PROCEDURE sp_CONSULTA_USUARIOS (
    IN p_INATIVO      BIT,
    IN p_NOME_USUARIO VARCHAR(30)
)
BEGIN
    SELECT ID_USUARIO,
           NOME_USUARIO,
           PRIVILEGIO,
           INATIVO,
           DATA_INICIO,
           DATA_EXPIRACAO,
           QUANTIDADE_CONEXOES,
           QUANTIDADE_CONECTADO,
           ALTERAR_SENHA_PRIMEIRO_LOGON,
           SENHA_POR_TRINTA_DIAS
      FROM USUARIOS
     WHERE INATIVO = p_INATIVO
       AND NOME_USUARIO LIKE p_NOME_USUARIO;
END //

DELIMITER ;
