CREATE TABLE IF NOT EXISTS TIPOS_TELEFONE (
    ID_TIPO_TELEFONE TINYINT AUTO_INCREMENT NOT NULL,
    DESCRICAO_TIPO_TELEFONE VARCHAR(25) NULL,
    MASCARA_TELEFONE VARCHAR(15) NULL,
    LOG_ID_USUARIO SMALLINT NOT NULL,
    LOG_ROTINA VARCHAR(1) NOT NULL,
    LOG_DATA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOG_MOTIVO_EXCLUSAO TEXT NULL,
    CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
    CONSTRAINT PK_TIPOS_TELEFONE PRIMARY KEY (ID_TIPO_TELEFONE),
    CONSTRAINT FK_TIPOS_TELEFONE_USUARIOS FOREIGN KEY (LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
