DROP PROCEDURE IF EXISTS sp_CONSULTA_TIPO_ENDERECO;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_TIPO_ENDERECO (
    IN p_ID_TIPO_ENDERECO TINYINT
)
BEGIN
    SELECT ID_TIPO_ENDERECO,
           DESCRICAO_TIPO_ENDERECO
      FROM TIPOS_ENDERECO
     WHERE ID_TIPO_ENDERECO = p_ID_TIPO_ENDERECO;
END //

DELIMITER ;
