CREATE TABLE IF NOT EXISTS BAIRROS (
   ID_BAIRRO INT AUTO_INCREMENT NOT NULL,
   ID_CIDADE SMALLINT NOT NULL,
   NOME_BAIRRO VARCHAR(70) NULL,
   DATA_VIGORACAO DATETIME NULL,
   INATIVO BIT DEFAULT 0,
   LOG_ID_USUARIO SMALLINT NOT NULL,
   LOG_ROTINA VARCHAR(1) NOT NULL,
   LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
   LOG_MOTIVO_EXCLUSAO VARCHAR(255) DEFAULT 'EXCLUSÃO PADRÃO',
   CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
   CONSTRAINT PK_BAIRROS PRIMARY KEY (ID_BAIRRO),
   CONSTRAINT FK_BAIRROS_CIDADES FOREIGN KEY (ID_CIDADE) REFERENCES CIDADES (ID_CIDADE),
   CONSTRAINT FK_BAIRROS_USUARIOS FOREIGN KEY (LOG_ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO)
);
