CREATE TABLE IF NOT EXISTS CIDADES (
   ID_CIDADE SMALLINT AUTO_INCREMENT NOT NULL,
   ID_ESTADO SMALLINT NOT NULL,
   NOME_CIDADE VARCHAR(45) NULL,
   CODIGO_IBGE INTEGER NULL,
   NUMERO_DDD TINYINT NULL,
   INATIVA BIT DEFAULT 0,
   LOG_ID_USUARIO SMALLINT NOT NULL,
   LOG_ROTINA VARCHAR(1) NOT NULL,
   LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
   LOG_MOTIVO_EXCLUSAO VARCHAR(255),
   CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
   CONSTRAINT PK_CIDADES PRIMARY KEY (ID_CIDADE),
   CONSTRAINT FK_CIDADES_ESTADOS FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO),
   CONSTRAINT FK_CIDADES_USUARIOS FOREIGN KEY (LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);