DROP PROCEDURE IF EXISTS sp_ALTERA_TIPO_TELEFONE;

DELIMITER //

CREATE PROCEDURE sp_ALTERA_TIPO_TELEFONE(
    IN p_ID_TIPO_TELEFONE        TINYINT,
    IN p_DESCRICAO_TIPO_TELEFONE VARCHAR(25),
    IN p_MASCARA_TELEFONE        VARCHAR(15),
    IN p_LOG_ID_USUARIO          SMALLINT
)
BEGIN
    UPDATE TIPOS_TELEFONE
       SET DESCRICAO_TIPO_TELEFONE = p_DESCRICAO_TIPO_TELEFONE,
           MASCARA_TELEFONE        = p_MASCARA_TELEFONE,
           LOG_ID_USUARIO          = p_LOG_ID_USUARIO,
           LOG_ROTINA              = 'A',
           LOG_DATA_HORA           = NOW()
     WHERE ID_TIPO_TELEFONE = p_ID_TIPO_TELEFONE;
END //

DELIMITER ;
