DROP PROCEDURE IF EXISTS sp_CONSULTA_TIPOS_TELEFONE;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_TIPOS_TELEFONE()
BEGIN
    SELECT ID_TIPO_TELEFONE,
           DESCRICAO_TIPO_TELEFONE,
           MASCARA_TELEFONE
      FROM TIPOS_TELEFONE
     ORDER BY ID_TIPO_TELEFONE;
END //

DELIMITER ;
