DROP PROCEDURE IF EXISTS sp_INSERE_TIPO_TELEFONE;

DELIMITER //

CREATE PROCEDURE sp_INSERE_TIPO_TELEFONE(
    IN  p_DESCRICAO_TIPO_TELEFONE VARCHAR(25),
    IN  p_MASCARA_TELEFONE        VARCHAR(15),
    IN  p_LOG_ID_USUARIO          SMALLINT,
    OUT p_ID_TIPO_TELEFONE        TINYINT
)
BEGIN
    INSERT INTO TIPOS_TELEFONE (
        DESCRICAO_TIPO_TELEFONE,
        MASCARA_TELEFONE,
        LOG_ID_USUARIO,
        LOG_ROTINA
    ) VALUES (
        p_DESCRICAO_TIPO_TELEFONE,
        p_MASCARA_TELEFONE,
        p_LOG_ID_USUARIO,
        'I'
    );

    SET p_ID_TIPO_TELEFONE = LAST_INSERT_ID();
END //

DELIMITER ;
