CREATE TABLE IF NOT EXISTS LOTEAMENTOS (
    ID_LOTEAMENTO SMALLINT AUTO_INCREMENT NOT NULL,
    ID_QUADRA SMALLINT NOT NULL,
    DESCRICAO_LOTEAMENTO VARCHAR(50) NULL,
    INATIVO BIT DEFAULT 0,
    LOG_ID_USUARIO SMALLINT NOT NULL,
    LOG_ROTINA CHAR(1) NOT NULL,
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    LOG_MOTIVO_EXCLUSAO VARCHAR(255)  DEFAULT 'EXCLUSÃO PADRÃO',
    CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
    CONSTRAINT PK_LOTEAMENTOS PRIMARY KEY (ID_LOTEAMENTO),
    CONSTRAINT FK_LOTEAMENTOS_QUADRAS FOREIGN KEY (ID_QUADRA) REFERENCES QUADRAS(ID_QUADRA),
    CONSTRAINT FK_LOTEAMENTOS_USUARIOS FOREIGN KEY (LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
