DROP PROCEDURE IF EXISTS sp_ALTERA_ESTADO_CIVIL;

DELIMITER //

CREATE PROCEDURE sp_ALTERA_ESTADO_CIVIL (
    IN p_ID_ESTADO_CIVIL        TINYINT,
    IN p_DESCRICAO_ESTADO_CIVIL VARCHAR(25),
    IN p_LOG_ID_USUARIO         SMALLINT
)
BEGIN
    UPDATE ESTADOS_CIVIS
       SET DESCRICAO_ESTADO_CIVIL = p_DESCRICAO_ESTADO_CIVIL,
           LOG_ID_USUARIO         = p_LOG_ID_USUARIO,
           LOG_ROTINA             = 'A',
           LOG_DATA_HORA          = NOW()
     WHERE ID_ESTADO_CIVIL = p_ID_ESTADO_CIVIL;
END//

DELIMITER ;
