DROP VIEW IF EXISTS vw_VIAS_BAIRROS;

CREATE VIEW vw_VIAS_BAIRROS AS
    SELECT VIAS.ID_VIA,
           VIAS.ID_LOGRADOURO,
           VIAS.ID_BAIRRO,
           VIAS.NOME_VIA,
           VIAS.CEP,
           VIAS.INATIVA,
           BAIRROS.NOME_BAIRRO,
           LOGRADOUROS.DESCRICAO_LOGRADOURO
      FROM VIAS
     INNER JOIN BAIRROS
	    ON BAIRROS.ID_BAIRRO = VIAS.ID_BAIRRO
     INNER JOIN LOGRADOUROS
	    ON LOGRADOUROS.ID_LOGRADOURO = VIAS.ID_LOGRADOURO;
