DROP PROCEDURE IF EXISTS sp_CONSULTA_ESTADOS_CIVIS;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_ESTADOS_CIVIS()
BEGIN
    SELECT ID_ESTADO_CIVIL,
           DESCRICAO_ESTADO_CIVIL
      FROM ESTADOS_CIVIS
     ORDER BY ID_ESTADO_CIVIL;
END//

DELIMITER ;
