DROP PROCEDURE IF EXISTS sp_EXCLUI_ESTADO_CIVIL;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_ESTADO_CIVIL (
    IN p_ID_ESTADO_CIVIL     TINYINT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE ESTADOS_CIVIS
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = NOW(),
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_ESTADO_CIVIL = p_ID_ESTADO_CIVIL;

    DELETE FROM ESTADOS_CIVIS
     WHERE ID_ESTADO_CIVIL = p_ID_ESTADO_CIVIL;
END//

DELIMITER ;
