CREATE TABLE IF NOT EXISTS TELEFONES_PESSOAS (
    ID_TELEFONE_PESSOA SMALLINT AUTO_INCREMENT,
    ID_PESSOA INT NOT NULL,
    ID_TIPO_TELEFONE TINYINT NULL,
    DDD_TELEFONE TINYINT NULL,
    DDI_TELEFONE SMALLINT NULL,
    NUMERO_TELEFONE VARCHAR(9) NULL,
    LOG_ID_USUARIO SMALLINT NOT NULL,
    LOG_ROTINA VARCHAR(1) NOT NULL,
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    LOG_MOTIVO_EXCLUSAO VARCHAR(255),
    CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
    CONSTRAINT PK_TELEFONES_PESSOAS PRIMARY KEY(ID_TELEFONE_PESSOA),
    CONSTRAINT FK_TELEFONES_PESSOAS_TIPOSTELEFONE FOREIGN KEY(ID_TIPO_TELEFONE) REFERENCES TIPOS_TELEFONE(ID_TIPO_TELEFONE),
    CONSTRAINT FK_TELEFONES_PESSOAS_PESSOAS FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA),
    CONSTRAINT FK_TELEFONES_PESSOAS_USUARIOS FOREIGN KEY (LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);