DROP VIEW IF EXISTS vw_LOTES_LOTEAMENTOS;

CREATE VIEW vw_LOTES_LOTEAMENTOS AS
    SELECT LOTES.ID_LOTE,
           LOTES.ID_LOTEAMENTO,
           LOTES.DESCRICAO_LOTE,
           LOTES.COMPLEMENTO,
           LOTES.INATIVO,
           LOTEAMENTOS.DESCRICAO_LOTEAMENTO
      FROM LOTES
     INNER JOIN LOTEAMENTOS
        ON LOTEAMENTOS.ID_LOTEAMENTO = LOTES.ID_LOTEAMENTO;
