DROP PROCEDURE IF EXISTS sp_CONSULTA_ESTADOS;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_ESTADOS (
    IN p_NOME_ESTADO VARCHAR(20),
    IN p_INATIVO     BIT
)
BEGIN
    SELECT ID_ESTADO,
           ID_PAIS,
           NOME_ESTADO,
           SIGLA_ESTADO,
           CODIGO_IBGE,
           INATIVO
           NOME_PAIS
      FROM vw_ESTADOS_PAISES
     WHERE INATIVO = p_INATIVO
       AND NOME_ESTADO LIKE p_NOME_ESTADO;
END//

DELIMITER ;
