DROP PROCEDURE IF EXISTS sp_CONSULTA_PAISES;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_PAISES (
    IN p_NOME_PAIS VARCHAR(50),
    IN p_INATIVO   BIT
)
BEGIN
    SELECT ID_PAIS,
           NOME_PAIS,
           SIGLA_02,
           SIGLA_03,
           CODIGO_ISO_3166,
           NUMERO_DDI,
           INATIVO
      FROM PAISES
     WHERE INATIVO = p_INATIVO
       AND NOME_PAIS LIKE p_NOME_PAIS;
END//

DELIMITER ;
