CREATE TABLE IF NOT EXISTS CONDOMINIOS (
    ID_CONDOMINIO SMALLINT AUTO_INCREMENT NOT NULL,
    ID_BAIRRO INT NOT NULL,      
    NOME_CONDOMINIO VARCHAR(50) NULL,
    INATIVO BIT DEFAULT 0,
    LOG_ID_USUARIO SMALLINT NOT NULL,
    LOG_ROTINA CHAR(1) NOT NULL,
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    LOG_MOTIVO_EXCLUSAO VARCHAR(255),
    CONCURRENCY_ID CHAR(36) NOT NULL DEFAULT (UUID()),
    CONSTRAINT PK_CONDOMINIOS PRIMARY KEY (ID_CONDOMINIO),
    CONSTRAINT FK_CONDOMINIOS_BAIRROS FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRROS(ID_BAIRRO),
    CONSTRAINT FK_CONDOMINIOS_USUARIOS FOREIGN KEY (LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
