DROP PROCEDURE IF EXISTS sp_EXCLUI_ESTADO;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_ESTADO (
    IN p_ID_ESTADO           SMALLINT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE ESTADOS
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = NOW(),
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_ESTADO = p_ID_ESTADO;

    DELETE FROM ESTADOS
     WHERE ID_ESTADO = p_ID_ESTADO;
END//

DELIMITER ;
