CREATE TABLE IF NOT EXISTS PESSOAS_JURIDICAS (
    ID_PESSOA_JURIDICA INT AUTO_INCREMENT,
    ID_PESSOA INT NOT NULL,
    CNPJ VARCHAR(14) NULL,
    RAZAO_SOCIAL VARCHAR(115) NULL,
    INSCRICAO_MUNICIPAL VARCHAR(20) NULL,
    INSCRICAO_ESTADUAL VARCHAR(20) NULL,
    NOME_FANTASIA VARCHAR(50) NULL,
    DATA_FUNDACAO DATE NULL,
    LOG_ID_USUARIO SMALLINT NOT NULL,
    LOG_ROTINA VARCHAR(1) NOT NULL,
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    LOG_MOTIVO_EXCLUSAO VARCHAR(255) DEFAULT 'EXCLUSÃO PADRÃO',
    CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
    CONSTRAINT PK_PESSOAS_JURIDICAS PRIMARY KEY(ID_PESSOA_JURIDICA),
    CONSTRAINT FK_PESSOAS_JURIDICAS_PESSOAS FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA),
    CONSTRAINT FK_PESSOAS_JURIDICAS_USUARIOS FOREIGN KEY (LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);