CREATE TABLE IF NOT EXISTS SUB_GRUPOS (
    ID_SUB_GRUPO SMALLINT AUTO_INCREMENT,
    ID_GRUPO SMALLINT NULL,
    NOME_SUB_GRUPO VARCHAR(35) NULL,
    LOG_ID_USUARIO SMALLINT NOT NULL,
    LOG_ROTINA VARCHAR(1) NOT NULL,
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    LOG_MOTIVO_EXCLUSAO VARCHAR(255),
    CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
    CONSTRAINT PK_SUB_GRUPOS PRIMARY KEY (ID_SUB_GRUPO),
    CONSTRAINT FK_SUB_GRUPOS_GRUPOS FOREIGN KEY(ID_GRUPO) REFERENCES GRUPOS(ID_GRUPO),
    CONSTRAINT FK_USUARIOS_SUB_GRUPOS FOREIGN KEY(LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);