DROP PROCEDURE IF EXISTS sp_EXCLUI_CIDADE;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_CIDADE(
    IN p_ID_CIDADE           SMALLINT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE CIDADES
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = NOW(),
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_CIDADE = p_ID_CIDADE;

    DELETE FROM CIDADES
     WHERE ID_CIDADE = p_ID_CIDADE;
END//

DELIMITER ;
