DROP VIEW IF EXISTS vw_INFORMACOES_PESSOAS;

DELIMITER //

CREATE VIEW vw_INFORMACOES_PESSOAS AS
    SELECT PESSOAS.ID_PESSOA,
           PESSOAS.ATIVO,
           PESSOAS.DATA_CADASTRO,
           PESSOAS.E_MAIL,
           PESSOAS_FISICAS.ID_ESTADO_CIVIL,
           PESSOAS_FISICAS.ID_CIDADE,
           PESSOAS_FISICAS.NOME,
           PESSOAS_FISICAS.NOME_PAI,
           PESSOAS_FISICAS.NOME_MAE,
           PESSOAS_FISICAS.IDENTIDADE,
           PESSOAS_FISICAS.CPF,
           PESSOAS_FISICAS.SEXO,
           PESSOAS_FISICAS.DATA_NASCIMENTO,
           PESSOAS_JURIDICAS.CNPJ,
           PESSOAS_JURIDICAS.RAZAO_SOCIAL,
           PESSOAS_JURIDICAS.INSCRICAO_MUNICIPAL,
           PESSOAS_JURIDICAS.INSCRICAO_ESTADUAL,
           PESSOAS_JURIDICAS.NOME_FANTASIA,
           PESSOAS_JURIDICAS.DATA_FUNDACAO,
           TELEFONES_PESSOAS.ID_TIPO_TELEFONE,
           TELEFONES_PESSOAS.DDD_TELEFONE,
           TELEFONES_PESSOAS.DDI_TELEFONE,
           TELEFONES_PESSOAS.NUMERO_TELEFONE,
           ENDERECOS_PESSOAS.ID_VIA,
           ENDERECOS_PESSOAS.ID_TIPO_ENDERECO,
           ENDERECOS_PESSOAS.ID_LOTEAMENTO,
           ENDERECOS_PESSOAS.ID_LOTE,
           ENDERECOS_PESSOAS.ID_QUADRA,
           ENDERECOS_PESSOAS.ID_CONDOMINIO,
           ENDERECOS_PESSOAS.ID_DISTRITO,
           ENDERECOS_PESSOAS.NUMERO,
           ENDERECOS_PESSOAS.COMPLEMENTO,
           DADOS_BANCARIOS_PESSOAS.ID_BANCO,
           DADOS_BANCARIOS_PESSOAS.NUM_AGENCIA,
           DADOS_BANCARIOS_PESSOAS.DIG_VERIF_AGENCIA,
           DADOS_BANCARIOS_PESSOAS.CONTA,
           DADOS_BANCARIOS_PESSOAS.DIG_VERIF_CONTA,
           DADOS_BANCARIOS_PESSOAS.TIPO_PAGTO_BANCARIO,
           DADOS_BANCARIOS_PESSOAS.TIPO_TRANS_PIX,
           DADOS_BANCARIOS_PESSOAS.TIPO_CHAVE_PIX,
           DADOS_BANCARIOS_PESSOAS.CHAVE_PIX
      FROM PESSOAS
      LEFT JOIN PESSOAS_FISICAS
        ON PESSOAS.ID_PESSOA = PESSOAS_FISICAS.ID_PESSOA
      LEFT JOIN PESSOAS_JURIDICAS
        ON PESSOAS.ID_PESSOA = PESSOAS_JURIDICAS.ID_PESSOA
	  LEFT JOIN TELEFONES_PESSOAS
        ON PESSOAS.ID_PESSOA = TELEFONES_PESSOAS.ID_PESSOA
	  LEFT JOIN ENDERECOS_PESSOAS
        ON PESSOAS.ID_PESSOA = ENDERECOS_PESSOAS.ID_PESSOA
      LEFT JOIN DADOS_BANCARIOS_PESSOAS
        ON PESSOAS.ID_PESSOA = DADOS_BANCARIOS_PESSOAS.ID_PESSOA;//

DELIMITER ;