CREATE TABLE IF NOT EXISTS UNIDADES (
    ID_UNIDADE SMALLINT AUTO_INCREMENT,
    SIGLA_UNIDADE VARCHAR(05) NULL,
    NOME_UNIDADE VARCHAR(25) NULL,
    QUEBRA_NA_ENTRADA CHAR(01) DEFAULT 'F',
    LOG_ID_USUARIO SMALLINT NOT NULL,
    LOG_ROTINA VARCHAR(1) NOT NULL,
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    LOG_MOTIVO_EXCLUSAO VARCHAR(255),
    CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
    CONSTRAINT PK_UNIDADES PRIMARY KEY (ID_UNIDADE),
    CONSTRAINT FK_UNIDADES_USUARIOS FOREIGN KEY(LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
