CREATE TABLE IF NOT EXISTS GRUPOS (
    ID_GRUPO  SMALLINT AUTO_INCREMENT NOT NULL,
    NOME_GRUPO VARCHAR(35) NULL,
    LOG_ID_USUARIO SMALLINT NOT NULL,
    LOG_ROTINA VARCHAR(1) NOT NULL,
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    LOG_MOTIVO_EXCLUSAO VARCHAR(255),
    CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
    CONSTRAINT PK_GRUPOS PRIMARY KEY (ID_GRUPO),
    CONSTRAINT FK_GRUPOS_USUARIOS FOREIGN KEY(LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);