DROP PROCEDURE IF EXISTS sp_INSERE_TIPO_ZONA;

DELIMITER //

CREATE PROCEDURE sp_INSERE_TIPO_ZONA(
    IN p_DESCRICAO_TIPO_ZONA VARCHAR(25),
    IN p_LOG_ID_USUARIO      SMALLINT,
    OUT p_ID_TIPO_ZONA       TINYINT
)
BEGIN
    INSERT INTO TIPOS_ZONA (
        DESCRICAO_TIPO_ZONA,
        LOG_ID_USUARIO,
        LOG_ROTINA
    ) VALUES (
        p_DESCRICAO_TIPO_ZONA,
        p_LOG_ID_USUARIO,
        'I'
    );

    SET p_ID_TIPO_ZONA = LAST_INSERT_ID();
END//

DELIMITER ;
