CREATE TABLE IF NOT EXISTS ZONAS (
   ID_ZONA SMALLINT AUTO_INCREMENT NOT NULL,
   ID_TIPO_ZONA TINYINT NULL,
   DESCRICAO_ZONA VARCHAR(50) NULL,
   INATIVA BIT DEFAULT 0,
   AREA_MINIMA DECIMAL(15, 3) NULL,
   TESTADA_MINIMA DECIMAL(15, 3) NULL,
   COMPLEMENTO_AREA_MINIMA VARCHAR(8) NULL,
   IDENTIFICADOR_ZONA VARCHAR(10) NULL,
   LOG_ID_USUARIO SMALLINT NOT NULL,
   LOG_ROTINA VARCHAR(1) NOT NULL,
   LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
   LOG_MOTIVO_EXCLUSAO TEXT DEFAULT NULL,
   CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
   CONSTRAINT PK_ZONAS PRIMARY KEY (ID_ZONA),
   CONSTRAINT FK_ZONAS_TIPOS_ZONAS FOREIGN KEY (ID_TIPO_ZONA) REFERENCES TIPOS_ZONA(ID_TIPO_ZONA),
   CONSTRAINT FK_ZONAS_USUARIOS FOREIGN KEY (LOG_ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

