DROP VIEW IF EXISTS vw_CIDADES_ESTADOS;

DELIMITER //

CREATE VIEW vw_CIDADES_ESTADOS AS 
    SELECT CIDADES.ID_CIDADE,
           CIDADES.ID_ESTADO,
           CIDADES.NOME_CIDADE,
           CIDADES.CODIGO_IBGE,
           CIDADES.NUMERO_DDD,
           CIDADES.INATIVA,
           ESTADOS.NOME_ESTADO
      FROM CIDADES
     INNER JOIN ESTADOS
	    ON ESTADOS.ID_ESTADO = CIDADES.ID_ESTADO//

DELIMITER ;