DROP PROCEDURE IF EXISTS sp_INSERE_DISTRITO;

DELIMITER //

CREATE PROCEDURE sp_INSERE_DISTRITO(
    IN  p_ID_CIDADE      SMALLINT,
    IN  p_NOME_DISTRITO  VARCHAR(50),
    IN  p_INATIVO        BIT,
    IN  p_LOG_ID_USUARIO SMALLINT,
    OUT p_ID_DISTRITO    SMALLINT
)
BEGIN
    INSERT INTO DISTRITOS (
        ID_CIDADE,
        NOME_DISTRITO,
        INATIVO,
        LOG_ID_USUARIO,
        LOG_ROTINA,
        LOG_DATA_HORA
    ) VALUES (
        p_ID_CIDADE,
        p_NOME_DISTRITO,
        p_INATIVO,
        p_LOG_ID_USUARIO,
        'I',
        NOW()
    );

    SET p_ID_DISTRITO = LAST_INSERT_ID();
END//

DELIMITER ;
