DROP PROCEDURE IF EXISTS sp_CONSULTA_LOGRADOURO;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_LOGRADOURO(
    IN p_ID_LOGRADOURO        SMALLINT,
    IN p_DESCRICAO_LOGRADOURO VARCHAR(25)
)
BEGIN
    SELECT ID_LOGRADOURO,
           DESCRICAO_LOGRADOURO,
           ABREVIATURA_LOGRADOURO,
           INATIVO
      FROM LOGRADOUROS
     WHERE ID_LOGRADOURO = p_ID_LOGRADOURO
        OR DESCRICAO_LOGRADOURO LIKE p_DESCRICAO_LOGRADOURO;
END//

DELIMITER ;
