DROP PROCEDURE IF EXISTS sp_INSERE_LOGRADOURO;

DELIMITER //

CREATE PROCEDURE sp_INSERE_LOGRADOURO(
    IN p_DESCRICAO_LOGRADOURO   VARCHAR(25),
    IN p_ABREVIATURA_LOGRADOURO VARCHAR(10),
    IN p_INATIVO                BIT,
    IN p_LOG_ID_USUARIO         SMALLINT,
    OUT p_ID_LOGRADOURO         SMALLINT
)
BEGIN
    INSERT INTO LOGRADOUROS (
        DESCRICAO_LOGRADOURO,
        ABREVIATURA_LOGRADOURO,
        INATIVO,
        LOG_ID_USUARIO,
        LOG_ROTINA,
        LOG_DATA_HORA
    ) VALUES (
        p_DESCRICAO_LOGRADOURO,
        p_ABREVIATURA_LOGRADOURO,
        p_INATIVO,
        p_LOG_ID_USUARIO,
        'I',
        NOW()
    );

    SET p_ID_LOGRADOURO = LAST_INSERT_ID();
END//

DELIMITER ;

