DROP PROCEDURE IF EXISTS sp_EXCLUI_BAIRRO;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_BAIRRO(
    IN p_ID_BAIRRO           INT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE BAIRROS
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = NOW(),
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_BAIRRO = p_ID_BAIRRO;

    DELETE FROM BAIRROS
     WHERE ID_BAIRRO = p_ID_BAIRRO;
END//

DELIMITER ;
