DROP VIEW IF EXISTS vw_BAIRROS_CIDADES;

DELIMITER //

CREATE VIEW vw_BAIRROS_CIDADES AS
    SELECT BAIRROS.ID_BAIRRO,
           BAIRROS.ID_CIDADE,
           BAIRROS.NOME_BAIRRO,
           BAIRROS.DATA_VIGORACAO,
           BAIRROS.INATIVO,
           CIDADES.NOME_CIDADE
      FROM BAIRROS
     INNER JOIN CIDADES
	    ON CIDADES.ID_CIDADE = BAIRROS.ID_CIDADE//

DELIMITER ;
