DROP PROCEDURE IF EXISTS sp_ALTERA_QUADRA;

DELIMITER //

CREATE PROCEDURE sp_ALTERA_QUADRA(
    IN p_ID_QUADRA        SMALLINT,
    IN p_ID_BAIRRO        INTEGER,
    IN p_DESCRICAO_QUADRA VARCHAR(35),
    IN p_COMPLEMENTO      VARCHAR(05),
    IN p_INATIVA          BIT,
    IN p_LOG_ID_USUARIO   SMALLINT
)
BEGIN
    UPDATE QUADRAS
       SET ID_BAIRRO        = p_ID_BAIRRO,
           DESCRICAO_QUADRA = p_DESCRICAO_QUADRA,
           COMPLEMENTO      = p_COMPLEMENTO,
           INATIVA          = p_INATIVA,
           LOG_ID_USUARIO   = p_LOG_ID_USUARIO,
           LOG_ROTINA       = 'A'
     WHERE ID_QUADRA = p_ID_QUADRA;
END//

DELIMITER ;
