DROP PROCEDURE IF EXISTS sp_CONSULTA_QUADRA;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_QUADRA(
    IN p_ID_QUADRA SMALLINT
)
BEGIN
    SELECT ID_QUADRA,
           ID_BAIRRO,
           DESCRICAO_QUADRA,
           COMPLEMENTO,
           INATIVA
      FROM QUADRAS
     WHERE ID_QUADRA = p_ID_QUADRA;
END//

DELIMITER ;
