DROP PROCEDURE IF EXISTS sp_CONSULTA_LOGRADOUROS;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_LOGRADOUROS()
BEGIN
    SELECT ID_LOGRADOURO,
           DESCRICAO_LOGRADOURO,
           ABREVIATURA_LOGRADOURO,
           INATIVO
      FROM LOGRADOUROS
     ORDER BY ID_LOGRADOURO;
END//

DELIMITER ;

