DROP PROCEDURE IF EXISTS sp_INSERE_LOTEAMENTO;

DELIMITER //

CREATE PROCEDURE sp_INSERE_LOTEAMENTO(
    IN  p_ID_QUADRA            SMALLINT,
    IN  p_DESCRICAO_LOTEAMENTO VARCHAR(50),
    IN  p_INATIVO              BIT,
    IN  p_LOG_ID_USUARIO       SMALLINT,
    OUT p_ID_LOTEAMENTO        SMALLINT
)
BEGIN
    INSERT INTO LOTEAMENTOS (
        ID_QUADRA,
        DESCRICAO_LOTEAMENTO,
        INATIVO,
        LOG_ID_USUARIO,
        LOG_ROTINA
    ) VALUES (
        p_ID_QUADRA,
        p_DESCRICAO_LOTEAMENTO,
        p_INATIVO,
        p_LOG_ID_USUARIO,
        'I'
    );

    SET p_ID_LOTEAMENTO = LAST_INSERT_ID();
END//

DELIMITER ;
