DROP PROCEDURE IF EXISTS sp_EXCLUI_VIA;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_VIA(
    IN p_ID_VIA              INT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE VIAS
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = NOW(),
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_VIA = p_ID_VIA;

    DELETE FROM VIAS
     WHERE ID_VIA = p_ID_VIA;
END//

DELIMITER ;
