DROP PROCEDURE IF EXISTS sp_ALTERA_LOTEAMENTO;

DELIMITER //

CREATE PROCEDURE sp_ALTERA_LOTEAMENTO(
    IN p_ID_LOTEAMENTO        SMALLINT,
    IN p_ID_QUADRA            SMALLINT,
    IN p_DESCRICAO_LOTEAMENTO VARCHAR(50),
    IN p_INATIVO              BIT,
    IN p_LOG_ID_USUARIO       SMALLINT
)
BEGIN
    UPDATE LOTEAMENTOS
       SET ID_QUADRA            = p_ID_QUADRA,
           DESCRICAO_LOTEAMENTO = p_DESCRICAO_LOTEAMENTO,
           INATIVO              = p_INATIVO,
           LOG_ID_USUARIO       = p_LOG_ID_USUARIO,
           LOG_ROTINA           = 'A',
           LOG_DATA_HORA        = NOW()
     WHERE ID_LOTEAMENTO = p_ID_LOTEAMENTO;
END//

DELIMITER ;
