DROP PROCEDURE IF EXISTS sp_ALTERA_LOTE;

DELIMITER //

CREATE PROCEDURE sp_ALTERA_LOTE(
    IN p_ID_LOTE        SMALLINT,
    IN p_ID_LOTEAMENTO  SMALLINT,
    IN p_DESCRICAO_LOTE VARCHAR(25),
    IN p_COMPLEMENTO    VARCHAR(20),
    IN p_INATIVO        BIT,
    IN p_LOG_ID_USUARIO SMALLINT
)
BEGIN
    UPDATE LOTES
       SET ID_LOTEAMENTO  = p_ID_LOTEAMENTO,
           DESCRICAO_LOTE = p_DESCRICAO_LOTE,
           COMPLEMENTO    = p_COMPLEMENTO,
           INATIVO        = p_INATIVO,
           LOG_ID_USUARIO = p_LOG_ID_USUARIO,
           LOG_ROTINA     = 'A',
           LOG_DATA_HORA  = NOW()
     WHERE ID_LOTE = p_ID_LOTE;
END//

DELIMITER ;
