DROP PROCEDURE IF EXISTS sp_CONSULTA_LOTE;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_LOTE(
    IN p_ID_LOTE SMALLINT
)
BEGIN
    SELECT ID_LOTE,
           ID_LOTEAMENTO,
           DESCRICAO_LOTE,
           COMPLEMENTO,
           INATIVO
      FROM LOTES
     WHERE ID_LOTE = p_ID_LOTE;
END//

DELIMITER ;
