DROP PROCEDURE IF EXISTS sp_INSERE_LOTE;

DELIMITER //

CREATE PROCEDURE sp_INSERE_LOTE(
    IN  p_ID_LOTEAMENTO  SMALLINT,
    IN  p_DESCRICAO_LOTE VARCHAR(25),
    IN  p_COMPLEMENTO    VARCHAR(20),
    IN  p_INATIVO        BIT,
    IN  p_LOG_ID_USUARIO SMALLINT,
    OUT p_ID_LOTE        SMALLINT
)
BEGIN
    INSERT INTO LOTES (
        ID_LOTEAMENTO,
        DESCRICAO_LOTE,
        COMPLEMENTO,
        INATIVO,
        LOG_ID_USUARIO,
        LOG_ROTINA
    ) VALUES (
        p_ID_LOTEAMENTO,
        p_DESCRICAO_LOTE,
        p_COMPLEMENTO,
        p_INATIVO,
        p_LOG_ID_USUARIO,
        'I'
    );

    SET p_ID_LOTE = LAST_INSERT_ID();
END//

DELIMITER ;
