DROP PROCEDURE IF EXISTS sp_CONSULTA_LOTEAMENTOS;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_LOTEAMENTOS(
    IN p_DESCRICAO_LOTEAMENTO VARCHAR(50),
    IN p_INATIVO              BIT
)
BEGIN
    SELECT ID_LOTEAMENTO,
           ID_QUADRA,
           DESCRICAO_LOTEAMENTO,
           INATIVO,
           DESCRICAO_QUADRA
      FROM vw_LOTEAMENTOS_QUADRAS
     WHERE INATIVO = p_INATIVO
       AND DESCRICAO_LOTEAMENTO LIKE p_DESCRICAO_LOTEAMENTO;
END//

DELIMITER ;
