DROP PROCEDURE IF EXISTS sp_EXCLUI_LOTEAMENTO;

DELIMITER //

CREATE PROCEDURE sp_EXCLUI_LOTEAMENTO(
    IN p_ID_LOTEAMENTO       SMALLINT,
    IN p_LOG_ID_USUARIO      SMALLINT,
    IN p_LOG_MOTIVO_EXCLUSAO VARCHAR(255)
)
BEGIN
    UPDATE LOTEAMENTOS
       SET LOG_ID_USUARIO      = p_LOG_ID_USUARIO,
           LOG_ROTINA          = 'E',
           LOG_DATA_HORA       = NOW(),
           LOG_MOTIVO_EXCLUSAO = p_LOG_MOTIVO_EXCLUSAO
     WHERE ID_LOTEAMENTO = p_ID_LOTEAMENTO;

    DELETE FROM LOTEAMENTOS
     WHERE ID_LOTEAMENTO = p_ID_LOTEAMENTO;
END//

DELIMITER ;
