DROP PROCEDURE IF EXISTS sp_INSERE_CONDOMINIO;

DELIMITER //

CREATE PROCEDURE sp_INSERE_CONDOMINIO(
    IN  p_ID_BAIRRO       INT,
    IN  p_NOME_CONDOMINIO VARCHAR(50),
    IN  p_INATIVO         BIT,
    IN  p_LOG_ID_USUARIO  SMALLINT,
    OUT p_ID_CONDOMINIO   SMALLINT
)
BEGIN
    INSERT INTO CONDOMINIOS (
        ID_BAIRRO,
        NOME_CONDOMINIO,
        INATIVO,
        LOG_ID_USUARIO,
        LOG_ROTINA
    ) VALUES (
        p_ID_BAIRRO,
        p_NOME_CONDOMINIO,
        p_INATIVO,
        p_LOG_ID_USUARIO,
        'I'
    );

    SET p_ID_CONDOMINIO = LAST_INSERT_ID();
END //

DELIMITER ;
