DROP PROCEDURE IF EXISTS sp_CONSULTA_LOTES;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_LOTES(
    IN p_DESCRICAO_LOTE VARCHAR(25),
    IN p_INATIVO        BIT
)
BEGIN
    SELECT ID_LOTE,
           ID_LOTEAMENTO,
           DESCRICAO_LOTE,
           COMPLEMENTO,
           INATIVO,
           DESCRICAO_LOTEAMENTO
      FROM vw_LOTES_LOTEAMENTOS
     WHERE INATIVO = p_INATIVO
       AND DESCRICAO_LOTE LIKE p_DESCRICAO_LOTE;
END //

DELIMITER ;
