DROP PROCEDURE IF EXISTS sp_CONSULTA_CONDOMINIO;

DELIMITER //

CREATE PROCEDURE sp_CONSULTA_CONDOMINIO(
    IN p_ID_CONDOMINIO SMALLINT
)
BEGIN
   SELECT ID_CONDOMINIO,
          ID_BAIRRO,
          NOME_CONDOMINIO,
          INATIVO
     FROM CONDOMINIOS
    WHERE ID_CONDOMINIO = p_ID_CONDOMINIO;
END//

DELIMITER ;
