DROP PROCEDURE IF EXISTS sp_ALTERA_CONDOMINIO;

DELIMITER //

CREATE PROCEDURE sp_ALTERA_CONDOMINIO(
    IN p_ID_CONDOMINIO   SMALLINT,
    IN p_ID_BAIRRO       INT,
    IN p_NOME_CONDOMINIO VARCHAR(50),
    IN p_INATIVO         BIT,
    IN p_LOG_ID_USUARIO  SMALLINT
)
BEGIN
    UPDATE CONDOMINIOS
       SET ID_BAIRRO       = p_ID_BAIRRO,
           NOME_CONDOMINIO = p_NOME_CONDOMINIO,
           INATIVO         = p_INATIVO,
           LOG_ID_USUARIO  = p_LOG_ID_USUARIO,
           LOG_ROTINA      = 'A',
           LOG_DATA_HORA   = NOW()
     WHERE ID_CONDOMINIO = p_ID_CONDOMINIO;
END//

DELIMITER ;
