DROP PROCEDURE IF EXISTS sp_INSERE_PESSOA;

DELIMITER //

CREATE PROCEDURE sp_INSERE_PESSOA(
    IN  p_ATIVO          TINYINT,
    IN  p_DATA_CADASTRO  DATE,
    IN  p_E_MAIL         VARCHAR(80),
    IN  p_LOG_ID_USUARIO SMALLINT,
    OUT p_ID_CONDOMINIO  SMALLINT
)
BEGIN
    INSERT INTO PESSOAS (
        ATIVO,
        DATA_CADASTRO,
        E_MAIL,
        LOG_ID_USUARIO,
        LOG_ROTINA
    ) VALUES (
        p_ATIVO,
        p_DATA_CADASTRO,
        p_E_MAIL,
        p_LOG_ID_USUARIO,
        'I'
    );

    SET p_ID_PESSOA = LAST_INSERT_ID();
END //

DELIMITER ;
