CREATE TABLE IF NOT EXISTS LOG_USUARIOS (
    ID_LOG_USUARIO INTEGER AUTO_INCREMENT,
    ID_USUARIO SMALLINT,
    ROTINA VARCHAR(1),
    DATA_HORA DATETIME,
    MOTIVO_EXCLUSAO TEXT,
    DADOS_ANTERIORES JSON,
    DADOS_POSTERIORES JSON,
    CON_CURRENCY_ID VARCHAR(50) NOT NULL DEFAULT (UUID()),
  CONSTRAINT PK_LOG_USUARIOS PRIMARY KEY(ID_LOG_USUARIO)
);