DELIMITER //

CREATE TRIGGER trg_LOG_USUARIOS_DELETE
AFTER DELETE ON USUARIOS
FOR EACH ROW
BEGIN
    INSERT INTO DADOS_LOG.LOG_USUARIOS (
        ID_USUARIO,
        ROTINA,
        DATA_HORA,
        MOTIVO_EXCLUSAO,
        DADOS_ANTERIORES
    ) VALUES (
        OLD.LOG_ID_USUARIO,
        OLD.LOG_ROTINA,
        OLD.LOG_DATA_HORA,
        OLD.LOG_MOTIVO_EXCLUSAO,
        JSON_OBJECT('ID_USUARIO', OLD.ID_USUARIO,
                    'NOME_USUARIO', OLD.NOME_USUARIO,
                    'PRIVILEGIO', OLD.PRIVILEGIO,
                    'SENHA', OLD.SENHA,
                    'INATIVO', OLD.INATIVO,
                    'DATA_INICIO', OLD.DATA_INICIO,
                    'DATA_EXPIRACAO', OLD.DATA_EXPIRACAO,
                    'QUANTIDADE_CONEXOES', OLD.QUANTIDADE_CONEXOES,
                    'QUANTIDADE_CONECTADO', OLD.QUANTIDADE_CONECTADO,
                    'ALTERAR_SENHA_PRIMEIRO_LOGON', OLD.ALTERAR_SENHA_PRIMEIRO_LOGON,
                    'SENHA_POR_TRINTA_DIAS', OLD.SENHA_POR_TRINTA_DIAS,
                    'CON_CURRENCY_ID', OLD.CON_CURRENCY_ID
                    )
    );
END//

DELIMITER ;