DELIMITER //

CREATE TRIGGER trg_LOG_USUARIOS_UPDATE
AFTER UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
    INSERT INTO DADOS_LOG.LOG_USUARIOS (
        ID_USUARIO,
        ROTINA,
        DATA_HORA,
        DADOS_ANTERIORES,
        DADOS_POSTERIORES
    ) VALUES (
        NEW.LOG_ID_USUARIO,
        NEW.LOG_ROTINA,
        NEW.LOG_DATA_HORA,
        JSON_OBJECT('ID_USUARIO', OLD.ID_USUARIO,
                    'NOME_USUARIO', OLD.NOME_USUARIO,
                    'PRIVILEGIO', OLD.PRIVILEGIO,
                    'SENHA', OLD.SENHA,
                    'INATIVO', OLD.INATIVO,
                    'DATA_INICIO', OLD.DATA_INICIO,
                    'DATA_EXPIRACAO', OLD.DATA_EXPIRACAO,
                    'QUANTIDADE_CONEXOES', OLD.QUANTIDADE_CONEXOES,
                    'QUANTIDADE_CONECTADO', OLD.QUANTIDADE_CONECTADO,
                    'ALTERAR_SENHA_PRIMEIRO_LOGON', OLD.ALTERAR_SENHA_PRIMEIRO_LOGON,
                    'SENHA_POR_TRINTA_DIAS', OLD.SENHA_POR_TRINTA_DIAS,
                    'CON_CURRENCY_ID', OLD.CON_CURRENCY_ID
                    ),
        JSON_OBJECT('ID_USUARIO', NEW.ID_USUARIO,
                    'NOME_USUARIO', NEW.NOME_USUARIO,
                    'PRIVILEGIO', NEW.PRIVILEGIO,
                    'SENHA', NEW.SENHA,
                    'INATIVO', NEW.INATIVO,
                    'DATA_INICIO', NEW.DATA_INICIO,
                    'DATA_EXPIRACAO', NEW.DATA_EXPIRACAO,
                    'QUANTIDADE_CONEXOES', NEW.QUANTIDADE_CONEXOES,
                    'QUANTIDADE_CONECTADO', NEW.QUANTIDADE_CONECTADO,
                    'ALTERAR_SENHA_PRIMEIRO_LOGON', NEW.ALTERAR_SENHA_PRIMEIRO_LOGON,
                    'SENHA_POR_TRINTA_DIAS', NEW.SENHA_POR_TRINTA_DIAS,
                    'CON_CURRENCY_ID', NEW.CON_CURRENCY_ID
                    )
    );
END//

DELIMITER ;