INSERT INTO BANCOS (NOME_BANCO, COD_BANCO, COD_ISPB, LOG_ID_USUARIO, LOG_ROTINA)
VALUES ('BANCO A.J. RENNER'                                                                      , '654', '92874270', 01, 'I'),
       ('BANCO ABC BRASIL'                                                                       , '246', '28195667', 01, 'I'),
       ('BANCO ABN AMRO'                                                                         , '075', '3532415', 01, 'I'),
       ('BANCO ALFA'                                                                             , '025', '3323840', 01, 'I'),
       ('BANCO ARBI'                                                                             , '213', '54403563', 01, 'I'),
       ('BANCO AZTECA DO BRASIL'                                                                 , '019', '9391857', 01, 'I'),
       ('BANCO BARCLAYS'                                                                         , '740', '61146577', 01, 'I'),
       ('BANCO BBM'                                                                              , '107', '15114366', 01, 'I'),
       ('BANCO BMFBOVESPA'                                                                       , '096', '997185', 01, 'I'),
       ('BANCO BMG'                                                                              , '318', '61186680', 01, 'I'),
       ('BANCO BNP PARIBAS BRASIL'                                                               , '752', '1522368', 01, 'I'),
       ('BANCO BOA VISTA INTERATLANTICO'                                                         , '248', '33485541', 01, 'I'),
       ('BANCO BONSUCESSO'                                                                       , '218', '71027866', 01, 'I'),
       ('BANCO BRACCE'                                                                           , '065', '48795256', 01, 'I'),
       ('BANCO BRADESCARD'                                                                       , '063', '4184779', 01, 'I'),
       ('BANCO BRADESCO BBI'                                                                     , '036', '60746948', 01, 'I'),
       ('BANCO BRADESCO CARTÕES'                                                                 , '204', '59438325', 01, 'I'),
       ('BANCO BRADESCO FINANCIAMENTOS'                                                          , '394', '7207996', 01, 'I'),
       ('BANCO BRADESCO'                                                                         , '237', '60746948', 01, 'I'),
       ('BANCO BTG PACTUAL'                                                                      , '208', '30306294', 01, 'I'),
       ('BANCO CACIQUE'                                                                          , '263', '33349358', 01, 'I'),
       ('BANCO CAIXA GERAL – BRASIL'                                                             , '473', '33466988', 01, 'I'),
       ('BANCO CAPITAL'                                                                          , '412', '15173776', 01, 'I'),
       ('BANCO CARGILL'                                                                          , '040', '3609817', 01, 'I'),
       ('BANCO CEDULA'                                                                           , '266', '33132044', 01, 'I'),
       ('BANCO CETELEM'                                                                          , '739', '558456', 01, 'I'),
       ('BANCO CIFRA'                                                                            , '233', '62421979', 01, 'I'),
       ('BANCO CITIBANK'                                                                         , '745', '33479023', 01, 'I'),
       ('BANCO CLÁSSICO'                                                                         , '241', '31597552', 01, 'I'),
       ('BANCO COOPERATIVO DO BRASIL – BANCOOB'                                                  , '756', '2038232', 01, 'I'),
       ('BANCO COOPERATIVO SICREDI'                                                              , '748', '1181521', 01, 'I'),
       ('BANCO CREDIT AGRICOLE BRASIL'                                                           , '222', '75647891', 01, 'I'),
       ('BANCO CREDIT SUISSE (BRASIL)'                                                           , '505', '32062580', 01, 'I'),
       ('BANCO DA AMAZONIA'                                                                      , '003', '4902979', 01, 'I'),
       ('BANCO DA CHINA BRASIL'                                                                  , '083', '10690848', 01, 'I'),
       ('BANCO DAYCOVAL'                                                                         , '707', '62232889', 01, 'I'),
       ('BANCO DE LA NACION ARGENTINA'                                                           , '300', '33042151', 01, 'I'),
       ('BANCO DE LA PROVINCIA DE BUENOS AIRES'                                                  , '495', '44189447', 01, 'I'),
       ('BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY'                                             , '494', '51938876', 01, 'I'),
       ('BANCO DE TOKYO MITSUBISHI UFJ BRASIL'                                                   , '456', '60498557', 01, 'I'),
       ('BANCO DIBENS'                                                                           , '214', '61199881', 01, 'I'),
       ('BANCO DO BRASIL'                                                                        , '001', '0', 01, 'I'),
       ('BANCO DO ESTADO DE SERGIPE'                                                             , '047', '13009717', 01, 'I'),
       ('BANCO DO ESTADO DO PARA'                                                                , '037', '4913711', 01, 'I'),
       ('BANCO DO ESTADO DO RIO GRANDE DO SUL (BANRISUL)'                                        , '041', '92702067', 01, 'I'),
       ('BANCO DO NORDESTE DO BRASIL'                                                            , '004', '7237373', 01, 'I'),
       ('BANCO FATOR'                                                                            , '265', '33644196', 01, 'I'),
       ('BANCO FIBRA'                                                                            , '224', '58616418', 01, 'I'),
       ('BANCO FICSA'                                                                            , '626', '61348538', 01, 'I'),
       ('BANCO GERADOR'                                                                          , '121', '10664513', 01, 'I'),
       ('BANCO GUANABARA'                                                                        , '612', '31880826', 01, 'I'),
       ('BANCO INDUSTRIAL DO BRASIL'                                                             , '604', '31895683', 01, 'I'),
       ('BANCO INDUSTRIAL E COMERCIAL'                                                           , '320', '7450604', 01, 'I'),
       ('BANCO INDUSVAL'                                                                         , '653', '61024352', 01, 'I'),
       ('BANCO INTERCAP'                                                                         , '630', '58497702', 01, 'I'),
       ('BANCO INTERMEDIUM'                                                                      , '077', '416968', 01, 'I'),
       ('BANCO INVESTCRED UNIBANCO'                                                              , '249', '61182408', 01, 'I'),
       ('BANCO ITAU BBA'                                                                         , '184', '17298092', 01, 'I'),
       ('BANCO ITAÚ HOLDING FINANCEIRA'                                                          , '652', '60872504', 01, 'I'),
       ('BANCO J. SAFRA'                                                                         , '074', '3017677', 01, 'I'),
       ('BANCO J.P. MORGAN'                                                                      , '376', '33172537', 01, 'I'),
       ('BANCO JOHN DEERE'                                                                       , '217', '91884981', 01, 'I'),
       ('BANCO KDB DO BRASIL'                                                                    , '076', '7656500', 01, 'I'),
       ('BANCO KEB DO BRASIL'                                                                    , '757', '2318507', 01, 'I'),
       ('BANCO LUSO BRASILEIRO'                                                                  , '600', '59118133', 01, 'I'),
       ('BANCO MERCANTIL DO BRASIL'                                                              , '389', '17184037', 01, 'I'),
       ('BANCO MIZUHO DO BRASIL'                                                                 , '370', '61088183', 01, 'I'),
       ('BANCO MODAL'                                                                            , '746', '30723886', 01, 'I'),
       ('BANCO MORGAN STANLEY DEAN WITTER'                                                       , '066', '2801938', 01, 'I'),
       ('BANCO MÁXIMA'                                                                           , '243', '33923798', 01, 'I'),
       ('BANCO ORIGINAL DO AGRONEGÓCIO'                                                          , '079', '9516419', 01, 'I'),
       ('BANCO ORIGINAL'                                                                         , '212', '92894922', 01, 'I'),
       ('BANCO PANAMERICANO'                                                                     , '623', '59285411', 01, 'I'),
       ('BANCO PAULISTA'                                                                         , '611', '61820817', 01, 'I'),
       ('BANCO PECUNIA'                                                                          , '613', '60850229', 01, 'I'),
       ('BANCO PETRA'                                                                            , '094', '11758741', 01, 'I'),
       ('BANCO PINE'                                                                             , '643', '62144175', 01, 'I'),
       ('BANCO POTTENCIAL'                                                                       , '735', '253448', 01, 'I'),
       ('BANCO RABOBANK INTERNATIONAL BRASIL'                                                    , '747', '1023570', 01, 'I'),
       ('BANCO RANDON'                                                                           , '088', '11476673', 01, 'I'),
       ('BANCO RENDIMENTO'                                                                       , '633', '68900810', 01, 'I'),
       ('BANCO RIBEIRAO PRETO'                                                                   , '741', '517645', 01, 'I'),
       ('BANCO RODOBENS'                                                                         , '120', '33603457', 01, 'I'),
       ('BANCO SAFRA'                                                                            , '422', '58160789', 01, 'I'),
       ('BANCO SANTANDER (BRASIL)'                                                               , '033', '90400888', 01, 'I'),
       ('BANCO SEMEAR'                                                                           , '743', '795423', 01, 'I'),
       ('BANCO SOCIETE GENERALE BRASIL'                                                          , '366', '61533584', 01, 'I'),
       ('BANCO SOFISA'                                                                           , '637', '60889128', 01, 'I'),
       ('BANCO SUMITOMO MITSUI BRASILEIRO'                                                       , '464', '60518222', 01, 'I'),
       ('BANCO TOPAZIO'                                                                          , '082', '7679404', 01, 'I'),
       ('BANCO TRIÂNGULO'                                                                        , '634', '17351180', 01, 'I'),
       ('BANCO VOTORANTIM'                                                                       , '655', '59588111', 01, 'I'),
       ('BANCO VR'                                                                               , '610', '78626983', 01, 'I'),
       ('BANCO WESTERN UNION DO BRASIL'                                                          , '119', '13720915', 01, 'I'),
       ('BANCO WOORI BANK DO BRASIL'                                                             , '124', '15357060', 01, 'I'),
       ('BANESTES (BANCO DO ESTADO DO ESPIRITO SANTO)'                                           , '021', '28127603', 01, 'I'),
       ('BANIF – BANCO INTERNACIONAL DO FUNCHAL (BRASIL)'                                        , '719', '33884941', 01, 'I'),
       ('BANK OF AMERICA MERRILL LYNCH BANCO MÚLTIPLO'                                           , '755', '62073200', 01, 'I'),
       ('BCV – BANCO DE CRÉDITO E VAREJO'                                                        , '250', '50585090', 01, 'I'),
       ('BES INVESTIMENTO DO BRASIL – BANCO DE INVESTIMENTO'                                     , '078', '34111187', 01, 'I'),
       ('BM TRICURY'                                                                             , '018', '57839805', 01, 'I'),
       ('BNY MELLON'                                                                             , '017', '42272526', 01, 'I'),
       ('BPN BRASIL BANCO MÚLTIPLO'                                                              , '069', '61033106', 01, 'I'),
       ('BRADESCO BERJ'                                                                          , '122', '33147315', 01, 'I'),
       ('BRASIL PLURAL BANCO MÚLTIPLO'                                                           , '125', '45246410', 01, 'I'),
       ('BRB – BANCO DE BRASÍLIA'                                                                , '070', '208', 01, 'I'),
       ('BRICKELL CRÉDITO, FINANCIAMENTO E INVESTIMENTO'                                         , '092', '12865507', 01, 'I'),
       ('CAIXA ECONOMICA FEDERAL'                                                                , '104', '360305', 01, 'I'),
       ('CC CREDICOAMO CRÉDITO RURAL COOPERATIVA'                                                , '010', '81723108', 01, 'I'),
       ('CC UNICRED BRASIL CENTRAL'                                                              , '112', '4243780', 01, 'I'),
       ('CC UNICRED DO BRASIL'                                                                   , '136', '315557', 01, 'I'),
       ('CC UNIPRIME NORTE DO PARANA'                                                            , '084', '2398976', 01, 'I'),
       ('CECOOPES – CENTRAL DAS COOPERATIVAS DE ECONOMIA E CRÉDITO MÚTUO'                        , '114', '5790149', 01, 'I'),
       ('CITIBANK N.A.'                                                                          , '477', '33042953', 01, 'I'),
       ('COOPERATIVA CENTRAL DE CRÉDITO DO ESTADO DE SP'                                         , '090', '73085573', 01, 'I'),
       ('COOPERATIVA CENTRAL DE CRÉDITO NOROESTE BRASILEIRO'                                     , '097', '4632856', 01, 'I'),
       ('COOPERATIVA CENTRAL DE CRÉDITO URBANO – CECRED'                                         , '085', '5463212', 01, 'I'),
       ('COOPERATIVA DE CRÉDITO RURAL DA REGIÃO DA MOGIANA'                                      , '089', '62109566', 01, 'I'),
       ('CREDIALIANCA COOPERATIVA DE CRÉDITO RURAL'                                              , '098', '78157146', 01, 'I'),
       ('DEUTSCHE BANK – BANCO ALEMÃO'                                                           , '487', '62331228', 01, 'I'),
       ('HIPERCARD BANCO MÚLTIPLO'                                                               , '062', '3012230', 01, 'I'),
       ('HSBC BANK BRASIL – BANCO MÚLTIPLO'                                                      , '399', '1701201', 01, 'I'),
       ('ICBC DO BRASIL BANCO MÚLTIPLO'                                                          , '132', '17453575', 01, 'I'),
       ('ING BANK N.V.'                                                                          , '492', '49336860', 01, 'I'),
       ('ITAÚ UNIBANCO'                                                                          , '341', '60701190', 01, 'I'),
       ('NOVO BANCO CONTINENTAL'                                                                 , '753', '74828799', 01, 'I'),
       ('PARANA BANCO'                                                                           , '254', '14388334', 01, 'I'),
       ('SCOTIABANK BRASIL BANCO MÚLTIPLO'                                                       , '751', '29030467', 01, 'I'),
       ('UNICRED CENTRAL RS – CENTRAL DE COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DO ESTADO DO RS', '091', '1634601', 01, 'I'),
       ('UNICRED CENTRAL SANTA CATARINA'                                                         , '087', '543968', 01, 'I'),
       ('UNIPRIME CENTRAL – CENTRAL INTERESTADUAL DE COOPERATIVA DE CRÉDITO'                     , '099', '3046391', 01, 'I');